# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 268eb9dbda841077e6c3314a8f3faf6d4655c9389771ea03c15834c49e0690f59102b91182e50ed75a638716e7f47dc85bb6927a218d57c0219c6f991d6b0753

test:
  secret_key_base: f9f43961e02bfc5b3a9bdb4e4c2d8a5fb481f29a7415908727f4e1f9c746d9b655d0a2af45be0fe6e8affa5f1b36739e791975aadeb66d020929582cd893fe6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
